
#端口号
server:
  port: 8081

#静态资源地址
localPath: E:\

#账号密码
name: root
pwd: 123


#<-------------以下不用作配置----------->
spring:
  mvc:
    static-path-pattern: /static/**
  resources:
    static-locations:
      - file:${localPath}
      - classpath:/META-INF/resources/
      - classpath:/resources/
      - classpath:/static/
      - classpath:/public/

staticAutorize: true



